language: php
services:
    - mysql
php:
    - 7.0
    - 7.1
    - 7.2
env:
    - CORE_BRANCH=stable14 DB=mysql

before_install:
    - wget https://phar.phpunit.de/phpunit-5.7.phar
    - chmod +x phpunit-5.7.phar
    - mkdir bin
    - mv phpunit-5.7.phar bin/phpunit
    - export PATH="$PWD/bin:$PATH"
    - phpunit --version
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh deck $CORE_BRANCH $DB
    - cd ../server
    - ./occ app:enable deck

before_script:
    - cd apps/deck

script:
    - composer install
    - make test-unit

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - cat ../../data/nextcloud.log

notifications:
  email: false
