sudo: required
dist: trusty
language: php
php:
    - 5.6
    - 7
env:
    global:
        - CORE_BRANCH=stable9
    matrix:
        - DB=pgsql

matrix:
    allow_failures:
        - env: DB=pgsql CORE_BRANCH=master
    include:
        - php: 5.6
          env: DB=sqlite
        - php: 5.6
          env: DB=mysql
        - php: 5.6
          env: DB=pgsql CORE_BRANCH=master
    fast_finish: true

before_install:
    # install firefox and enable a display for running JavaScript tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - sudo apt-get -y install python3-setuptools firefox mariadb-server
    - sudo easy_install3 requests ocdev
    - nvm install 5.9
    - npm install -g npm@latest
    - make
    # install core
    - cd ../
    - ocdev setup core --dir owncloud --branch $CORE_BRANCH --no-history
    - mv deck owncloud/apps/

before_script:
    - createuser -U travis -s oc_autotest
    - mysql -u root -e 'create database oc_autotest;'
    - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
    - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
    - cd owncloud
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable deck
    - ocdev server &
    - cd apps/deck

script:
    - make test