language: php
services:
    - mysql
php:
    - 5.6
    - 7
env:
    matrix:
        - CORE_BRANCH=master DB=sqlite 
        - CORE_BRANCH=master DB=mysql
        - CORE_BRANCH=stable11 DB=sqlite 
        - CORE_BRANCH=stable11 DB=mysql 

before_install:
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh deck $CORE_BRANCH $DB
    - cd ../server
    - ./occ app:enable deck
    - ./occ app:check-code deck
    - php -S localhost:8080 &

before_script:
    - cd apps/deck

script:
    - make test

after_failure:
    - cat ../../data/nextcloud.log

after_success:
    - bash <(curl -s https://codecov.io/bash)
