name: Package build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up npm7
      run: npm i -g npm@7
    - name: Setup PHP
      uses: shivammathur/setup-php@2.20.1
      with:
        php-version: '7.4'
        tools: composer
    - name: install dependencies
      run: |
        wget https://github.com/ChristophWurst/krankerl/releases/download/v0.12.2/krankerl_0.12.2_amd64.deb
        sudo dpkg -i krankerl_0.12.2_amd64.deb
    - name: package
      run: |
        uname -a
        RUST_BACKTRACE=1 krankerl --version
        RUST_BACKTRACE=1 krankerl package
    - uses: actions/upload-artifact@v3
      with:
        name: Deck app tarball
        path: build/artifacts/deck.tar.gz
